name: Build Android Only
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
  workflow_dispatch:
jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter: stable
      - name: 提前删掉项目签名配置，规避key.properties缺失报错
        run: |
          rm -f android/key.properties
      - name: 安装依赖库
        run: sudo apt update && sudo apt install clang libssl-dev
      - name: 配置Rust安卓编译链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - run: flutter pub get
      # 改用--debug 调试包，不需要签名文件
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: Venera_Debug_APK
          path: build/app/outputs/flutter-apk/*.apk
