name: Prepare Project for Local Build (with full cache)

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
      - run: flutter pub get

      # 确认 pub 缓存中 git 依赖存在
      - name: List git cache
        run: ls -la ~/.pub-cache/git

      # 使用 --dereference 解决软链接，确保全部打入
      - name: Pack pub cache
        run: tar -czf pub-cache.tar.gz --dereference -C ~/.pub-cache .

      - uses: actions/upload-artifact@v4
        with:
          name: pub-cache-only
          path: pub-cache.tar.gz
